apiVersion: batch/v1
kind: CronJob
metadata:
  name: sidecar-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sidecar-user
            image: zwindler/sidecar-user
          initContainers:
          - name: slow-sidecar
            image: zwindler/slow-sidecar
            restartPolicy: Always
            ports:
            - containerPort: 8081
            startupProbe:
              httpGet:
                path: /
                port: 8081
              initialDelaySeconds: 5
              periodSeconds: 1
              failureThreshold: 5
          restartPolicy: Never